'use client';

import { useState, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { FrictionMoment, FrictionReceipt as FrictionReceiptType, CATEGORY_META, FrictionCategory } from '@/lib/types';
import { getMoments, getSettings, addReceipt, getReceipts } from '@/lib/storage';

function ReceiptContent() {
  const searchParams = useSearchParams();
  const [moments, setMoments] = useState<FrictionMoment[]>([]);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [receipt, setReceipt] = useState<FrictionReceiptType | null>(null);
  const [editableReceipt, setEditableReceipt] = useState<Partial<FrictionReceiptType>>({});
  const [loading, setLoading] = useState(false);
  const [savedReceipts, setSavedReceipts] = useState<FrictionReceiptType[]>([]);
  const [viewMode, setViewMode] = useState<'create' | 'view'>('create');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const loadedMoments = getMoments();
    setMoments(loadedMoments);
    setSavedReceipts(getReceipts());

    const momentId = searchParams.get('momentId');
    if (momentId) {
      setSelectedIds(new Set([momentId]));
    }
  }, [searchParams]);

  const toggleSelection = (id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const generateReceipt = async () => {
    const selected = moments.filter((m) => selectedIds.has(m.id));
    if (selected.length === 0) return;

    setLoading(true);
    try {
      const settings = getSettings();
      const res = await fetch('/api/receipt', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ moments: selected, settings }),
      });
      const data = await res.json();

      setEditableReceipt({
        whatHappened: data.whatHappened,
        whatIExperienced: data.whatIExperienced,
        whatHelpedPreviously: data.whatHelpedPreviously,
        whatIWantAdultsToKnow: data.whatIWantAdultsToKnow,
      });
      setReceipt(data);
    } catch (err) {
      console.error('Receipt generation failed:', err);
    } finally {
      setLoading(false);
    }
  };

  const saveReceipt = () => {
    if (!editableReceipt.whatHappened) return;

    const saved = addReceipt({
      createdAt: new Date().toISOString(),
      momentIds: Array.from(selectedIds),
      whatHappened: editableReceipt.whatHappened || '',
      whatIExperienced: editableReceipt.whatIExperienced || '',
      whatHelpedPreviously: editableReceipt.whatHelpedPreviously || '',
      whatIWantAdultsToKnow: editableReceipt.whatIWantAdultsToKnow || '',
      studentEdited: true,
    });

    setSavedReceipts([...savedReceipts, saved]);
    setReceipt(null);
    setEditableReceipt({});
    setSelectedIds(new Set());
  };

  const copyReceipt = () => {
    const text = `FRICTION RECEIPT
Generated by FrictionTrace — Student-owned accommodation evidence

What Happened:
${editableReceipt.whatHappened}

What I Experienced:
${editableReceipt.whatIExperienced}

What Helped Previously:
${editableReceipt.whatHelpedPreviously}

What I Want Adults to Know:
${editableReceipt.whatIWantAdultsToKnow}

---
"Nothing about me without me."
This receipt was created and shared by the student.`;

    navigator.clipboard.writeText(text);
  };

  const formatTime = (ts: string) => {
    const d = new Date(ts);
    return d.toLocaleString('en-US', {
      weekday: 'short',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  if (!mounted) return null;

  return (
    <div>
      <div className="page-header">
        <h1 className="page-title">Friction Receipt</h1>
        <p className="page-subtitle">
          Create a student-owned document that explains what happened — on your terms.
        </p>
      </div>

      {/* Tab toggle */}
      <div className="filter-bar" style={{ marginBottom: '24px' }}>
        <button
          className={`filter-pill ${viewMode === 'create' ? 'active' : ''}`}
          onClick={() => setViewMode('create')}
        >
          ✏️ Create New
        </button>
        <button
          className={`filter-pill ${viewMode === 'view' ? 'active' : ''}`}
          onClick={() => setViewMode('view')}
        >
          📋 Saved ({savedReceipts.length})
        </button>
      </div>

      {viewMode === 'create' && (
        <>
          {moments.length === 0 ? (
            <div className="empty-state">
              <div className="empty-state-icon">📋</div>
              <h3 className="empty-state-title">No moments to include</h3>
              <p className="empty-state-text">
                Log some friction moments first, then come back to create your receipt.
              </p>
            </div>
          ) : !receipt ? (
            <>
              <p style={{ fontSize: '14px', color: 'var(--text-secondary)', marginBottom: '16px' }}>
                Select the moments you want to include in your Friction Receipt:
              </p>

              {moments
                .sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime())
                .map((moment) => (
                  <div
                    key={moment.id}
                    className="moment-select"
                    style={{ marginBottom: '8px' }}
                  >
                    <button
                      className={`moment-checkbox ${selectedIds.has(moment.id) ? 'checked' : ''}`}
                      onClick={() => toggleSelection(moment.id)}
                      aria-pressed={selectedIds.has(moment.id)}
                    >
                      {selectedIds.has(moment.id) ? '✓' : ''}
                    </button>
                    <div className="moment-card" style={{ flex: 1, cursor: 'pointer' }} onClick={() => toggleSelection(moment.id)}>
                      <span className="moment-time">{formatTime(moment.timestamp)}</span>
                      <div className="moment-body">
                        <div className="moment-categories">
                          {moment.categories.length > 0
                            ? moment.categories.map((cat) => {
                                const meta = CATEGORY_META[cat as FrictionCategory];
                                return (
                                  <span
                                    key={cat}
                                    className="moment-category-tag"
                                    style={{ color: meta?.color }}
                                  >
                                    {meta?.icon} {meta?.label}
                                  </span>
                                );
                              })
                            : (
                              <span className="moment-category-tag" style={{ color: 'var(--text-muted)' }}>
                                ⚡ Something was hard
                              </span>
                            )}
                        </div>
                        {moment.textNote && (
                          <p className="moment-note">&ldquo;{moment.textNote}&rdquo;</p>
                        )}
                      </div>
                    </div>
                  </div>
                ))}

              <div style={{ textAlign: 'center', marginTop: '24px' }}>
                <button
                  className="btn btn-primary"
                  onClick={generateReceipt}
                  disabled={selectedIds.size === 0 || loading}
                  style={{ padding: '14px 32px', fontSize: '15px' }}
                >
                  {loading ? (
                    <>
                      <span className="spinner" style={{ width: '16px', height: '16px' }} />
                      Generating receipt...
                    </>
                  ) : (
                    `Generate receipt (${selectedIds.size} moment${selectedIds.size !== 1 ? 's' : ''})`
                  )}
                </button>
              </div>
            </>
          ) : (
            <div className="step-enter">
              <p style={{
                fontSize: '13px',
                color: 'var(--accent-amber)',
                textAlign: 'center',
                marginBottom: '20px',
                fontWeight: '500'
              }}>
                ✏️ You can edit every field below — this is YOUR document.
              </p>

              <div className="receipt-preview">
                <div className="receipt-header">
                  <div className="receipt-header-icon">📋</div>
                  <div className="receipt-header-title">Friction Receipt</div>
                  <div className="receipt-header-date">
                    {new Date().toLocaleDateString('en-US', {
                      weekday: 'long',
                      year: 'numeric',
                      month: 'long',
                      day: 'numeric',
                    })}
                  </div>
                </div>

                <div className="receipt-section">
                  <div className="receipt-section-label">What Happened</div>
                  <div className="receipt-section-content">
                    <textarea
                      value={editableReceipt.whatHappened || ''}
                      onChange={(e) => setEditableReceipt({ ...editableReceipt, whatHappened: e.target.value })}
                      rows={3}
                    />
                  </div>
                </div>

                <div className="receipt-section">
                  <div className="receipt-section-label">What I Experienced</div>
                  <div className="receipt-section-content">
                    <textarea
                      value={editableReceipt.whatIExperienced || ''}
                      onChange={(e) => setEditableReceipt({ ...editableReceipt, whatIExperienced: e.target.value })}
                      rows={3}
                    />
                  </div>
                </div>

                <div className="receipt-section">
                  <div className="receipt-section-label">What Helped Previously</div>
                  <div className="receipt-section-content">
                    <textarea
                      value={editableReceipt.whatHelpedPreviously || ''}
                      onChange={(e) => setEditableReceipt({ ...editableReceipt, whatHelpedPreviously: e.target.value })}
                      rows={3}
                    />
                  </div>
                </div>

                <div className="receipt-section">
                  <div className="receipt-section-label">What I Want Adults to Know</div>
                  <div className="receipt-section-content">
                    <textarea
                      value={editableReceipt.whatIWantAdultsToKnow || ''}
                      onChange={(e) => setEditableReceipt({ ...editableReceipt, whatIWantAdultsToKnow: e.target.value })}
                      rows={3}
                    />
                  </div>
                </div>

                <div className="receipt-footer">
                  &ldquo;Nothing about me without me.&rdquo; — This receipt is student-authored and student-controlled.
                </div>
              </div>

              <div className="receipt-actions">
                <button className="btn btn-secondary" onClick={copyReceipt}>
                  📋 Copy text
                </button>
                <button className="btn btn-primary" onClick={saveReceipt}>
                  💾 Save receipt
                </button>
                <button className="btn btn-ghost" onClick={() => { setReceipt(null); setEditableReceipt({}); }}>
                  Start over
                </button>
              </div>

              <p style={{
                fontSize: '12px',
                color: 'var(--text-muted)',
                textAlign: 'center',
                marginTop: '16px'
              }}>
                Share only if YOU choose to. Nothing is sent automatically.
              </p>
            </div>
          )}
        </>
      )}

      {viewMode === 'view' && (
        <>
          {savedReceipts.length === 0 ? (
            <div className="empty-state">
              <div className="empty-state-icon">📋</div>
              <h3 className="empty-state-title">No saved receipts</h3>
              <p className="empty-state-text">
                Create and save a Friction Receipt to see it here.
              </p>
            </div>
          ) : (
            savedReceipts.map((r) => (
              <div key={r.id} className="glass-card" style={{ marginBottom: '16px' }}>
                <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginBottom: '12px' }}>
                  Created {formatTime(r.createdAt)} · {r.momentIds.length} moment{r.momentIds.length !== 1 ? 's' : ''}
                </div>
                <div style={{ marginBottom: '12px' }}>
                  <div className="receipt-section-label">What Happened</div>
                  <p style={{ fontSize: '14px', color: 'var(--text-secondary)' }}>{r.whatHappened}</p>
                </div>
                <div style={{ marginBottom: '12px' }}>
                  <div className="receipt-section-label">What I Want Adults to Know</div>
                  <p style={{ fontSize: '14px', color: 'var(--text-primary)' }}>{r.whatIWantAdultsToKnow}</p>
                </div>
              </div>
            ))
          )}
        </>
      )}
    </div>
  );
}

export default function ReceiptPage() {
  return (
    <Suspense fallback={<div className="p-8 text-center text-slate-400">Loading receipt data...</div>}>
      <ReceiptContent />
    </Suspense>
  );
}
